algoritmo "Exercicio44"
var
   inicial, final, incremento: Inteiro
inicio
      Escreva("Valor inicial: ")
      Leia(inicial)
      Escreva("Valor final: ")
      Leia(final)
      Escreva("Incremento: ")
      Leia(incremento)
      Enquanto (inicial <= final) faca
               Escreva(inicial)
               inicial <- inicial + incremento
      FimEnquanto
      Escreva(" Acabou!")
fimalgoritmo